In [3]:
import pandas as pd
pd.set_option('max_colwidth', -1)

products = pd.read_json('product_metadata.json',orient='records')
#products = pd.json_normalize('product_metadata.json')

products.head(40)

/var/folders/c6/j_vv349941d370ftdw7xkzkw0000gn/T/ipykernel_47202/1964310699.py:2: FutureWarning: Passing a negative integer is deprecated in version 1.0 and will not be supported in future version. Instead, use None to not limit the column width.
  pd.set_option('max_colwidth', -1)

,DeliFresh,GardenGoodies,FlavoCrunch,NaturiBlend,SupraSavor,YumTastic
SandwichHam 250g,"{'price': 400, 'p_weight': 43}",NaN,NaN,NaN,NaN,NaN
Chorizo 6pc,"{'price': 800, 'p_weight': 6}",NaN,NaN,NaN,NaN,NaN
LiverSpread 150g,"{'price': 450, 'p_weight': 4}",NaN,NaN,NaN,NaN,NaN
SunflowerSeeds 600g,NaN,"{'price': 275, 'p_weight': 13}",NaN,NaN,NaN,NaN
HydroponicLettuce 1kg,NaN,"{'price': 350, 'p_weight': 18}",NaN,NaN,NaN,NaN
CornFlakes 500g,NaN,NaN,"{'price': 399, 'p_weight': 34}",NaN,NaN,NaN
OatCrunch 500g,NaN,NaN,"{'price': 449, 'p_weight': 21}",NaN,NaN,NaN
HoneyLoops 500g,NaN,NaN,"{'price': 429, 'p_weight': 29}",NaN,NaN,NaN
WholeBeanCoffee 600g,NaN,NaN,NaN,"{'price': 410, 'p_weight': 15}",NaN,NaN
BreakfastTea 25pc,NaN,NaN,NaN,"{'price': 325, 'p_weight': 13}",NaN,NaN
PocketPie 1pc,NaN,NaN,NaN,NaN,"{'price': 59, 'p_weight': 14}",NaN
BeefTapa 600g,NaN,NaN,NaN,NaN,"{'price': 399, 'p_weight': 15}",NaN
Hotdogs 4pc,NaN,NaN,NaN,NaN,NaN,"{'price': 240, 'p_weight': 15}"
LuncheonMeat 300g,NaN,NaN,NaN,NaN,NaN,"{'price': 299, 'p_weight': 12}"

In [4]:
sales = pd.read_json('grocery_product_sales.json')
sales.head(10)

,customer_id,retailer,products,total,invoice_id
0,15799,SavoryCorner,YumTastic Hotdogs 4pc (x4)|SupraSavor BeefTapa 600g (x2),1758,0
1,9332,FreshMart Express,"NaturiBlend WholeBeanCoffee 600g (x1),FlavoCrunch CornFlakes 500g (x1),NaturiBlend BreakfastTea 25pc (x1),YumTastic Hotdogs 4pc (x1),YumTastic LuncheonMeat 300g (x1)",1673,1
2,37804,SavoryCorner,GardenGoodies SunflowerSeeds 600g (x3)|YumTastic Hotdogs 4pc (x1)|GardenGoodies HydroponicLettuce 1kg (x1)|DeliFresh SandwichHam 250g (x1),1815,2
3,13276,FreshMart Express,"YumTastic LuncheonMeat 300g (x1),FlavoCrunch OatCrunch 500g (x1),GardenGoodies HydroponicLettuce 1kg (x1)",1098,3
4,64323,GourmetGrove,DeliFresh SandwichHam 250g (x1),400,4
5,532,GourmetGrove,SupraSavor BeefTapa 600g (x2);SupraSavor PocketPie 1pc (x1);DeliFresh Chorizo 6pc (x1),1657,5
6,26056,FreshMart Express,GardenGoodies SunflowerSeeds 600g (x1),275,6
7,13528,GourmetGrove,SupraSavor PocketPie 1pc (x1);YumTastic LuncheonMeat 300g (x1);NaturiBlend BreakfastTea 25pc (x1),683,7
8,43335,GourmetGrove,FlavoCrunch HoneyLoops 500g (x2);FlavoCrunch CornFlakes 500g (x1);FlavoCrunch OatCrunch 500g (x1);YumTastic Hotdogs 4pc (x1),1946,8
9,21635,GourmetGrove,YumTastic Hotdogs 4pc (x5),1200,9

In [5]:
sales = sales.dropna()
#sales.isna()
#sales.dtypes

In [6]:
sales['products'] = sales['products'].astype(str)
sales['products'] = sales['products'].str.split(r'[,|;]')
sales = sales.explode('products', ignore_index=True)

sales['products'] = sales['products'].astype(str)

sales[['products', 'quantity']] = sales['products'].str.split('(', n=1, expand=True)

sales.head(10)

,customer_id,retailer,products,total,invoice_id,quantity
0,15799,SavoryCorner,YumTastic Hotdogs 4pc,1758,0,x4)
1,15799,SavoryCorner,SupraSavor BeefTapa 600g,1758,0,x2)
2,9332,FreshMart Express,NaturiBlend WholeBeanCoffee 600g,1673,1,x1)
3,9332,FreshMart Express,FlavoCrunch CornFlakes 500g,1673,1,x1)
4,9332,FreshMart Express,NaturiBlend BreakfastTea 25pc,1673,1,x1)
5,9332,FreshMart Express,YumTastic Hotdogs 4pc,1673,1,x1)
6,9332,FreshMart Express,YumTastic LuncheonMeat 300g,1673,1,x1)
7,37804,SavoryCorner,GardenGoodies SunflowerSeeds 600g,1815,2,x3)
8,37804,SavoryCorner,YumTastic Hotdogs 4pc,1815,2,x1)
9,37804,SavoryCorner,GardenGoodies HydroponicLettuce 1kg,1815,2,x1)

In [7]:
sales['quantity'] = sales['quantity'].astype(str)
sales['quantity'] = sales['quantity'].str.extract(r'(\d)')
sales['quantity'] = sales['quantity'].astype(int)

sales.head(10)

,customer_id,retailer,products,total,invoice_id,quantity
0,15799,SavoryCorner,YumTastic Hotdogs 4pc,1758,0,4
1,15799,SavoryCorner,SupraSavor BeefTapa 600g,1758,0,2
2,9332,FreshMart Express,NaturiBlend WholeBeanCoffee 600g,1673,1,1
3,9332,FreshMart Express,FlavoCrunch CornFlakes 500g,1673,1,1
4,9332,FreshMart Express,NaturiBlend BreakfastTea 25pc,1673,1,1
5,9332,FreshMart Express,YumTastic Hotdogs 4pc,1673,1,1
6,9332,FreshMart Express,YumTastic LuncheonMeat 300g,1673,1,1
7,37804,SavoryCorner,GardenGoodies SunflowerSeeds 600g,1815,2,3
8,37804,SavoryCorner,YumTastic Hotdogs 4pc,1815,2,1
9,37804,SavoryCorner,GardenGoodies HydroponicLettuce 1kg,1815,2,1

In [8]:
products.head(40)

,DeliFresh,GardenGoodies,FlavoCrunch,NaturiBlend,SupraSavor,YumTastic
SandwichHam 250g,"{'price': 400, 'p_weight': 43}",NaN,NaN,NaN,NaN,NaN
Chorizo 6pc,"{'price': 800, 'p_weight': 6}",NaN,NaN,NaN,NaN,NaN
LiverSpread 150g,"{'price': 450, 'p_weight': 4}",NaN,NaN,NaN,NaN,NaN
SunflowerSeeds 600g,NaN,"{'price': 275, 'p_weight': 13}",NaN,NaN,NaN,NaN
HydroponicLettuce 1kg,NaN,"{'price': 350, 'p_weight': 18}",NaN,NaN,NaN,NaN
CornFlakes 500g,NaN,NaN,"{'price': 399, 'p_weight': 34}",NaN,NaN,NaN
OatCrunch 500g,NaN,NaN,"{'price': 449, 'p_weight': 21}",NaN,NaN,NaN
HoneyLoops 500g,NaN,NaN,"{'price': 429, 'p_weight': 29}",NaN,NaN,NaN
WholeBeanCoffee 600g,NaN,NaN,NaN,"{'price': 410, 'p_weight': 15}",NaN,NaN
BreakfastTea 25pc,NaN,NaN,NaN,"{'price': 325, 'p_weight': 13}",NaN,NaN
PocketPie 1pc,NaN,NaN,NaN,NaN,"{'price': 59, 'p_weight': 14}",NaN
BeefTapa 600g,NaN,NaN,NaN,NaN,"{'price': 399, 'p_weight': 15}",NaN
Hotdogs 4pc,NaN,NaN,NaN,NaN,NaN,"{'price': 240, 'p_weight': 15}"
LuncheonMeat 300g,NaN,NaN,NaN,NaN,NaN,"{'price': 299, 'p_weight': 12}"

In [9]:
products['Brand'] = products.notna().idxmax(axis=1)
products['Info'] = products[['DeliFresh','GardenGoodies','FlavoCrunch','NaturiBlend','SupraSavor','YumTastic']].bfill(axis=1).iloc[:, 0].fillna('unknown')
products['price'] = products['Info'].apply(lambda x: x['price'])
products.head(5)

,DeliFresh,GardenGoodies,FlavoCrunch,NaturiBlend,SupraSavor,YumTastic,Brand,Info,price
SandwichHam 250g,"{'price': 400, 'p_weight': 43}",NaN,NaN,NaN,NaN,NaN,DeliFresh,"{'price': 400, 'p_weight': 43}",400
Chorizo 6pc,"{'price': 800, 'p_weight': 6}",NaN,NaN,NaN,NaN,NaN,DeliFresh,"{'price': 800, 'p_weight': 6}",800
LiverSpread 150g,"{'price': 450, 'p_weight': 4}",NaN,NaN,NaN,NaN,NaN,DeliFresh,"{'price': 450, 'p_weight': 4}",450
SunflowerSeeds 600g,NaN,"{'price': 275, 'p_weight': 13}",NaN,NaN,NaN,NaN,GardenGoodies,"{'price': 275, 'p_weight': 13}",275
HydroponicLettuce 1kg,NaN,"{'price': 350, 'p_weight': 18}",NaN,NaN,NaN,NaN,GardenGoodies,"{'price': 350, 'p_weight': 18}",350

In [10]:
#products.rename(columns={products.columns[0]: 'Product'}, inplace=True)
#products.head(5)

In [11]:
sales['products'] = sales['products'].astype(str)
sales['Brand'] = sales['products'].str.split().str[0]
products = products.reset_index()

In [12]:
sales['products'] = sales['products'].str.split().str[1:]

#sales = pd.merge(sales,products[['price','index']],left_on='products',right_on='index',how='left')
sales.head(5)

,customer_id,retailer,products,total,invoice_id,quantity,Brand
0,15799,SavoryCorner,"[Hotdogs, 4pc]",1758,0,4,YumTastic
1,15799,SavoryCorner,"[BeefTapa, 600g]",1758,0,2,SupraSavor
2,9332,FreshMart Express,"[WholeBeanCoffee, 600g]",1673,1,1,NaturiBlend
3,9332,FreshMart Express,"[CornFlakes, 500g]",1673,1,1,FlavoCrunch
4,9332,FreshMart Express,"[BreakfastTea, 25pc]",1673,1,1,NaturiBlend

In [25]:
# separate into sep rows, split by ( and get quantity, multiply that by price in products

#sales['total_price'] = sales['price'] * sales['quantity']

# 1. yumtastic products


yum = sales[sales['Brand']=='YumTastic']
#yum.head(5)
yum.groupby('Brand').size()

Brand
YumTastic    75736
dtype: int64